--  This package was generated by the Ada_Drivers_Library project wizard script
package ADL_Config is
   Board                          : constant String  := "MicroBit";          -- From user input
   Architecture                   : constant String  := "ARM";               -- From board definition
   Vendor                         : constant String  := "Nordic";            -- From board definition
   Device_Family                  : constant String  := "nRF51";             -- From board definition
   Device_Name                    : constant String  := "nRF51822xxAA";      -- From board definition
   CPU_Core                       : constant String  := "ARM Cortex-M0";     -- From mcu definition
   Has_ZFP_Runtime                : constant String  := "True";              -- From board definition
   Has_Ravenscar_SFP_Runtime      : constant String  := "True";              -- From board definition
   Has_Ravenscar_Full_Runtime     : constant String  := "True";              -- From board definition
   Runtime_Profile                : constant String  := "ravenscar-sfp";     -- From user input
   Runtime_Name_Suffix            : constant String  := "microbit";          -- From board definition
   Runtime_Name                   : constant String  := "ravenscar-sfp-microbit"; -- From user input
   Max_Path_Length                : constant         := 1024;                -- From user input
   Max_Mount_Points               : constant         := 2;                   -- From user input
   Max_Mount_Name_Length          : constant         := 128;                 -- From user input
end ADL_Config;
